In [27]:
!pip install requests pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [28]:
import requests
import pandas as pd
import numpy as np

In [29]:
url = "https://www.lazada.co.id/catalog/?ajax=true&q=wardah"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
data = response.json()

items = data.get("mods", {}).get("listItems", [])

produk = []
harga = []
lokasi = []
rating = []


for item in items:
    produk.append(item.get("name"))
    harga.append(item.get("price"))
    lokasi.append(item.get("location"))
    rating.append(item.get("ratingScore"))

df = pd.DataFrame({
    "Produk": produk,
    "Harga": harga,
    "Lokasi": lokasi,
    "Rating": rating,
})

df

,Produk,Harga,Lokasi,Rating
0,WARDAH Collagen Moisturizer - Plump & Firm Rec...,127680,Kab. Bekasi,4.929304446978335
1,WARDAH Lightening Fresh BB Tint 15ml - Base Ma...,33580,Kab. Bekasi,4.908523908523908
2,[Lipcare brighten lips] Wardah hydration lip c...,28520,Kab. Bekasi,4.914423885618167
3,WARDAH Perfect Bright Moisturizer Bright + Oil...,29925,Kab. Sidoarjo,4.918234194360716
4,Wardah perfect bright creamy foam bright + smo...,20700,Kab. Bekasi,4.91701831518017
5,Wardah Glycolic Acid Niacinamide ADV Brighteni...,28520,Kab. Bekasi,4.935416803449106
6,WARDAH Refill Exclusive Two Way Cake - Bedak D...,59800,Kab. Sidoarjo,4.935072284817616
7,Wardah UV shield tinted tone up Sunscreen SPF ...,72580,Kab. Bekasi,4.907898749618786
8,KOREAN BLUR LIPS ANTI CRACK WARDAH Colorfit Ve...,73508,Kab. Bekasi,4.882795818196944
9,Wardah UV shield bright C-Hydrating Sunscreen ...,36340,Kab. Bekasi,4.930503808476901
10,Wardah Soft Body Scrub with Olive 240 ml - Bod...,56905,Kab. Bekasi,4.945945945945946
11,WARDAH C-Defense Vitamin C All Series Lengkap ...,39900,Kab. Bekasi,4.933260393873085
12,Wardah 3% Tranexamic Acid + Alpha Arbutin Crys...,95580,Kab. Bekasi,4.942231159147083
13,Wardah Scentsation Eau De Toilette 35 ml - Wom...,55660,Kab. Bekasi,4.941444237533623
14,WARDAH Lightening Face Mist 60 ml - Face Mist ...,28980,Kab. Bekasi,4.913801783659379
15,WARDAH Lightening Matte Powder 20 g Bedak Tabu...,38640,Kab. Bekasi,4.891389283539679
16,[Save] Wardah refill Lightening Powder Foundat...,36340,Kab. Bekasi,4.921760645375914
17,WARDAH Glasting Liquid Lip - Hi-Pigmented Glas...,90980,Kab. Bekasi,4.905424072198176
18,Wardah Soft Body Scrub 150 ml - Moisturizing B...,47405,Kab. Bekasi,4.931873479318734
19,Wardah Lip Cream-matte lip cream 4 G Warna int...,63940,Kab. Bekasi,4.880952380952381
20,WARDAH Lightening Liquid Foundation 25ml - Bas...,52440,Kab. Bekasi,4.94772832637923
21,[TWINPACK] WARDAH Crystal Secret NMF Amino + A...,72940,Kab. Bekasi,4.937210706379553
22,Wardah Scentsation Body Mist 100 ml - Long-Las...,38640,Kab. Bekasi,4.935294793701873
23,WARDAH Matte Lip Cream 4 g Warna Intense dan T...,63940,Kab. Bekasi,4.8575568805583815
24,[12.12] Wardah triple pack UV Shield Sunscreen...,140620,Kab. Bekasi,4.921339733798821
25,WARDAH Crystal Secret Series Lengkap - Milk Cl...,38180,Kab. Bekasi,4.933800127307448
26,[REFAL HADY'S FAVORITE] NEW! WARDAH Renew You ...,40940,Kab. Bekasi,4.940608116102062
27,Wardah UV Shield Sunscreen All Series - SPF 35...,36340,Kab. Bekasi,4.911108445297505
28,Wardah Micellar Water All Series - Perfect Bri...,29925,Kab. Bekasi,4.932357395254922
29,"Wardah Shampoo 160ml Twinpack Anti Hairfall, A...",50050,Kab. Sidoarjo,4.935854475825754
30,WARDAH Renew You Retinol Microcaps Matrixyl 30...,54740,Kab. Bekasi,4.93426032581866
31,WARDAH Crystal Secret α-Arbutin 5% Niacinamide...,55100,Kab. Bekasi,4.9311762543035735
32,Wardah acnederm salicylic acid zinc acne clear...,23920,Kab. Bekasi,4.908727090818136
33,Wardah 5% niacamide + bisabolol moisturizer li...,51060,Kab. Bekasi,4.941220872190703
34,WARDAH UV Shield Aqua Fresh Sunscreen Serum SP...,58900,Kab. Bekasi,4.9319790192323705
35,Wardah perfect bright creamy foam bright + oil...,21375,Kab. Bekasi,4.914738568045181
36,WARDAH Paket Crystal Secret - Brightening Day ...,98800,Kab. Bekasi,4.924265505984766
37,[CREATOR PICKS] WARDAH Lightening Fresh BB Tin...,34675,Kab. Bekasi,4.9190718732314656
38,Wardah Crystal Secret Bright-Peptide ™ 5% Ni...,55100,Kab. Banjar,4.939090171368561
39,Wardah perfect bright cooling jelly facial foa...,32775,Kab. Bekasi,4.912239347234814

In [30]:
df.describe()

,Produk,Harga,Lokasi,Rating
count,40,40,40,40
unique,40,33,3,40
top,WARDAH Collagen Moisturizer - Plump & Firm Rec...,36340,Kab. Bekasi,4.929304446978335
freq,1,3,36,1

In [31]:
df.sort_values("Harga")

,Produk,Harga,Lokasi,Rating
0,WARDAH Collagen Moisturizer - Plump & Firm Rec...,127680,Kab. Bekasi,4.929304446978335
24,[12.12] Wardah triple pack UV Shield Sunscreen...,140620,Kab. Bekasi,4.921339733798821
4,Wardah perfect bright creamy foam bright + smo...,20700,Kab. Bekasi,4.91701831518017
35,Wardah perfect bright creamy foam bright + oil...,21375,Kab. Bekasi,4.914738568045181
32,Wardah acnederm salicylic acid zinc acne clear...,23920,Kab. Bekasi,4.908727090818136
2,[Lipcare brighten lips] Wardah hydration lip c...,28520,Kab. Bekasi,4.914423885618167
5,Wardah Glycolic Acid Niacinamide ADV Brighteni...,28520,Kab. Bekasi,4.935416803449106
14,WARDAH Lightening Face Mist 60 ml - Face Mist ...,28980,Kab. Bekasi,4.913801783659379
3,WARDAH Perfect Bright Moisturizer Bright + Oil...,29925,Kab. Sidoarjo,4.918234194360716
28,Wardah Micellar Water All Series - Perfect Bri...,29925,Kab. Bekasi,4.932357395254922
39,Wardah perfect bright cooling jelly facial foa...,32775,Kab. Bekasi,4.912239347234814
1,WARDAH Lightening Fresh BB Tint 15ml - Base Ma...,33580,Kab. Bekasi,4.908523908523908
37,[CREATOR PICKS] WARDAH Lightening Fresh BB Tin...,34675,Kab. Bekasi,4.9190718732314656
9,Wardah UV shield bright C-Hydrating Sunscreen ...,36340,Kab. Bekasi,4.930503808476901
16,[Save] Wardah refill Lightening Powder Foundat...,36340,Kab. Bekasi,4.921760645375914
27,Wardah UV Shield Sunscreen All Series - SPF 35...,36340,Kab. Bekasi,4.911108445297505
25,WARDAH Crystal Secret Series Lengkap - Milk Cl...,38180,Kab. Bekasi,4.933800127307448
15,WARDAH Lightening Matte Powder 20 g Bedak Tabu...,38640,Kab. Bekasi,4.891389283539679
22,Wardah Scentsation Body Mist 100 ml - Long-Las...,38640,Kab. Bekasi,4.935294793701873
11,WARDAH C-Defense Vitamin C All Series Lengkap ...,39900,Kab. Bekasi,4.933260393873085
26,[REFAL HADY'S FAVORITE] NEW! WARDAH Renew You ...,40940,Kab. Bekasi,4.940608116102062
18,Wardah Soft Body Scrub 150 ml - Moisturizing B...,47405,Kab. Bekasi,4.931873479318734
29,"Wardah Shampoo 160ml Twinpack Anti Hairfall, A...",50050,Kab. Sidoarjo,4.935854475825754
33,Wardah 5% niacamide + bisabolol moisturizer li...,51060,Kab. Bekasi,4.941220872190703
20,WARDAH Lightening Liquid Foundation 25ml - Bas...,52440,Kab. Bekasi,4.94772832637923
30,WARDAH Renew You Retinol Microcaps Matrixyl 30...,54740,Kab. Bekasi,4.93426032581866
38,Wardah Crystal Secret Bright-Peptide ™ 5% Ni...,55100,Kab. Banjar,4.939090171368561
31,WARDAH Crystal Secret α-Arbutin 5% Niacinamide...,55100,Kab. Bekasi,4.9311762543035735
13,Wardah Scentsation Eau De Toilette 35 ml - Wom...,55660,Kab. Bekasi,4.941444237533623
10,Wardah Soft Body Scrub with Olive 240 ml - Bod...,56905,Kab. Bekasi,4.945945945945946
34,WARDAH UV Shield Aqua Fresh Sunscreen Serum SP...,58900,Kab. Bekasi,4.9319790192323705
6,WARDAH Refill Exclusive Two Way Cake - Bedak D...,59800,Kab. Sidoarjo,4.935072284817616
23,WARDAH Matte Lip Cream 4 g Warna Intense dan T...,63940,Kab. Bekasi,4.8575568805583815
19,Wardah Lip Cream-matte lip cream 4 G Warna int...,63940,Kab. Bekasi,4.880952380952381
7,Wardah UV shield tinted tone up Sunscreen SPF ...,72580,Kab. Bekasi,4.907898749618786
21,[TWINPACK] WARDAH Crystal Secret NMF Amino + A...,72940,Kab. Bekasi,4.937210706379553
8,KOREAN BLUR LIPS ANTI CRACK WARDAH Colorfit Ve...,73508,Kab. Bekasi,4.882795818196944
17,WARDAH Glasting Liquid Lip - Hi-Pigmented Glas...,90980,Kab. Bekasi,4.905424072198176
12,Wardah 3% Tranexamic Acid + Alpha Arbutin Crys...,95580,Kab. Bekasi,4.942231159147083
36,WARDAH Paket Crystal Secret - Brightening Day ...,98800,Kab. Bekasi,4.924265505984766

In [32]:
df.to_csv("lazada_wardah.csv", index=False)

# **INTERPRETASI DAN PENJELASAN**

Metode yang digunakan pada pengumpulan data ini adalah metode web scraping untuk mengambil data produk dari website Lazada secara otomatis dengan bantuan bahasa pemrograman Python.

> Web scraping merupakan teknik penumpulan data dari sebuah situs web dengan cara mengakses struktur data yang tersedia pada halaman tersebut, kemudian mengekstrak informasi yang dibutuhkan.

Pada program ini, kami menggunakan beberapa library Python, yaitu

> 'requests' digunakan untuk mengirim HTTP request untuk melakukan pengambilan data dari website,

> 'pandas' untuk mengolah data dan menyusun data hasil scraping menjadi bentuk tabel (dataframe) sehingga lebih mudah dianalisis,

>'numpy' untuk membantu operasi numerik dan manipulasi array.


Selanjutnya, program meminta alamat URL yang akan dijadikan sumber data karena URL tersebut langsung mengarah pada hasil pencarian produk Wardah di Lazada.

Pada program kami juga menambahkan 'headers request' untuk menyamarkan request Python karena website e-commerce biasanya memiliki sistem keamanan untuk mendeteksi bot scraping. Oleh karena itu, program kami menambahkan User-Agent agar server menganggap permintaan berasal dari browser biasa.

Setelah itu program mengirimkan permintaan ke server Lazada menggunakan fungsi 'requests.get()'. Hasil dari permintaan tersebut kemudian disimpan dalam variabel response.

Data yang diterima dari server masih dalam format JSON, sehingga pada tahap berikutnya data tersebut dikonversi menggunakan fungsi 'response.json()'. Proses ini mengubah data menjadi struktur data Python berupa dictionary yang dapat diakses berdasarkan key tertentu. Dari struktur JSON tersebut, informasi produk berada pada bagian mods yang kemudian di dalamnya terdapat 'listItems' yang berisi daftar produk hasil pencarian.

Setelah mendapatkan daftar produk, program kemudian membuat beberapa list kosong yang digunakan untuk menampung informasi penting dari setiap produk. Informasi yang diambil meliputi nama produk, harga produk, lokasi penjual, dan rating produk. Program kemudian melakukan perulangan menggunakan for loop untuk membaca setiap item produk yang terdapat pada listItems. Pada setiap iterasi, program mengambil data yang diperlukan menggunakan fungsi 'get()' agar proses tetap berjalan meskipun terdapat data yang kosong atau tidak tersedia pada suatu produk.

Setiap informasi yang berhasil diambil kemudian dimasukkan ke dalam list yang telah disiapkan sebelumnya. Setelah seluruh produk diproses, data yang tersimpan pada list tersebut digabungkan dan diubah menjadi sebuah DataFrame menggunakan library pandas. DataFrame ini memiliki struktur tabel dengan lima kolom utama, yaitu produk, harga, lokasi, dan rating. Dengan bentuk DataFrame ini, data menjadi lebih mudah untuk dianalisis, diproses lebih lanjut, maupun disimpan dalam bentuk file seperti CSV.

> Berdasarkan dataset yang dihasilkan, program berhasil mengumpulkan 40 data produk Wardah dari hasil pencarian di Lazada.

> Setiap baris pada dataset mewakili satu produk dengan informasi nama produk, harga, lokasi penjual, serta rating dari pengguna.

> Dari data yang diperoleh dapat terlihat bahwa harga produk Wardah pada hasil pencarian tersebut memiliki rentang yang cukup bervariasi, mulai dari sekitar Rp20.000 hingga mendekati Rp200.000, yang menunjukkan bahwa produk Wardah umumnya berada pada kategori kosmetik dengan harga yang relatif terjangkau bagi konsumen.

Secara keseluruhan, proses web scraping yang dilakukan pada kodingan ini berhasil mengumpulkan 40 entry data produk Wardah dari Lazada secara otomatis dan mengubahnya menjadi dataset yang terstruktur. Dengan memanfaatkan teknik web scraping, proses pengumpulan data yang sebelumnya harus dilakukan secara manual dapat dilakukan dengan lebih cepat, efisien, dan dalam jumlah data yang lebih besar.